export type TaskEvent = {
    "TaskPriority": string,
    "EventType": string,
    "WorkflowName": string,
    "Timestamp": string,
    "TaskAge": string,
    "TaskAssignmentStatus": string,
    "TaskAttributes": string,
    "TaskVersion": string,
    "TaskChannelUniqueName": string,
    "WorkspaceName": string,
    "OperatingUnitSid": string,
    "TaskChannelSid": string,
    "TaskQueueEnteredDate": string,
    "TaskDateCreated": string,
    "ResourceType": string,
    "TaskQueueName": string,
    "WorkflowSid": string,
    "AccountSid": string,
    "Sid": string,
    "TimestampMs": string,
    "TaskQueueTargetExpression": string,
    "WorkspaceSid": string,
    "TaskQueueSid": string,
    "EventDescription": string,
    "TaskSid": string,
    "ResourceSid": string,
}